# This is a basic workflow to help you get started with Actions

name: Bintray Publish

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  release:
    types: [ created, prereleased ]
  push:
    tags:
      - '*-dev*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish-mirai:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Init gradle project
        run: ./gradlew clean --info

      - name: Check keys
        run: >
          ./gradlew :mirai-core-utils:ensureBintrayAvailable
          :mirai-core-api:ensureBintrayAvailable
          :mirai-core:ensureBintrayAvailable
          :mirai-console:ensureBintrayAvailable
          -Dbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_user=${{ secrets.BINTRAY_USER }}
          -Dbintray_key=${{ secrets.BINTRAY_KEY }} -Pbintray_key=${{ secrets.BINTRAY_KEY }}

      - name: fillBuildConstants
        run: >
          ./gradlew
          fillBuildConstants --info --stacktrace
          -Dbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_user=${{ secrets.BINTRAY_USER }}
          -Dbintray_key=${{ secrets.BINTRAY_KEY }} -Pbintray_key=${{ secrets.BINTRAY_KEY }}

      - name: Assemble
        run: ./gradlew assemble --info --stacktrace

      - name: Check
        run: ./gradlew check --info --stacktrace

      - name: Gradle :mirai-core-utils:publish
        run: >
          ./gradlew :mirai-core-utils:publish --info --stacktrace
          -Dbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_user=${{ secrets.BINTRAY_USER }}
          -Dbintray_key=${{ secrets.BINTRAY_KEY }} -Pbintray_key=${{ secrets.BINTRAY_KEY }}

      - name: Gradle :mirai-core-api:publish
        run: >
          ./gradlew :mirai-core-api:publish --info --stacktrace
          -Dbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_user=${{ secrets.BINTRAY_USER }}
          -Dbintray_key=${{ secrets.BINTRAY_KEY }} -Pbintray_key=${{ secrets.BINTRAY_KEY }}

      - name: Gradle :mirai-core:publish
        run: >
          ./gradlew :mirai-core:publish --info --stacktrace
          -Dbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_user=${{ secrets.BINTRAY_USER }}
          -Dbintray_key=${{ secrets.BINTRAY_KEY }} -Pbintray_key=${{ secrets.BINTRAY_KEY }}

      - name: Gradle :mirai-core-all:bintrayUpload
        run: >
          ./gradlew :mirai-core-all:bintrayUpload --info
          -Dbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_user=${{ secrets.BINTRAY_USER }}
          -Dbintray_key=${{ secrets.BINTRAY_KEY }} -Pbintray_key=${{ secrets.BINTRAY_KEY }}

      - name: Gradle :mirai-console:bintrayUpload
        run: >
          ./gradlew
          :mirai-console:bintrayUpload --info
          -Dbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_user=${{ secrets.BINTRAY_USER }}
          -Dbintray_key=${{ secrets.BINTRAY_KEY }} -Pbintray_key=${{ secrets.BINTRAY_KEY }}

      - name: Gradle :mirai-console-terminal:bintrayUpload
        run: >
          ./gradlew
          :mirai-console-terminal:bintrayUpload --info
          -Dbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_user=${{ secrets.BINTRAY_USER }}
          -Dbintray_key=${{ secrets.BINTRAY_KEY }} -Pbintray_key=${{ secrets.BINTRAY_KEY }}

      - name: Gradle :mirai-console-compiler-common:bintrayUpload
        run: >
          ./gradlew
          :mirai-console-compiler-common:bintrayUpload --info
          -Dbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_user=${{ secrets.BINTRAY_USER }}
          -Dbintray_key=${{ secrets.BINTRAY_KEY }} -Pbintray_key=${{ secrets.BINTRAY_KEY }}

      - name: Gradle :mirai-console-intellij:bintrayUpload
        run: >
          ./gradlew
          :mirai-console-intellij:bintrayUpload --info
          -Dbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_user=${{ secrets.BINTRAY_USER }}
          -Dbintray_key=${{ secrets.BINTRAY_KEY }} -Pbintray_key=${{ secrets.BINTRAY_KEY }}

      - name: Publish Gradle plugin
        run: >
          ./gradlew
          :mirai-console-gradle:publishPlugins --info --stacktrace
          -Dgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
          -Dgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
